### PR TITLE
Change README.md, add AUTHORS.md and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dalebrubaker**

### CODE REVIEW

**Comment by dalebrubaker** [comment]
This build will fail until the latest pre-release NuGet for NetMQ picks up commits through Feb 6.

**Comment by somdoron** [comment]
Which commits do you need? I will release it...

**Comment by dalebrubaker** [comment]
1.  Commit 330c8da7ff14b99c165427133ed73866d1a23ddf Expose NetMQBeacon.BoundTo. Use it in Bus.
2.  Commit ab21e0b51c749539bd86c159768cc824d259871a Simplify NetMQBeacon receive methods.

But I don’t mean to push you. This can wait for NetMQ4 if you’d prefer. No one is waiting for this, as far as I know.

Thanks.

**Comment by somdoron** [comment]
Just implemented automated releasing for version 3, I will do the same for NetMQ4 tomorrow, so hopefully will release a version tomorrow.

**Pull request merged**
